### Setting up a quick and dirty simple autoencoder

In [1]:
import numpy as np
import torch as th

c:\Users\osc16\miniconda3\envs\d2d\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [2]:
from AutoEncoder import MarketAutoencoder 


### Try Training it

In [3]:
# Load input data
import pickle
with open("1.6kRunDemo.pkl","rb") as fp:
    paths = pickle.load(fp)


In [4]:
# Train
autoencoder = MarketAutoencoder()
autoencoder.train(paths)

Epoch1, Batch 1000 loss: 0.43646489664428245
Epoch1, Batch 3000 loss: 0.02615692541221935
Epoch1, Batch 5000 loss: 0.02573225842581218
Epoch1, Batch 7000 loss: 0.025481427626339023
Epoch2, Batch 1000 loss: 0.029583406717520286
Epoch2, Batch 3000 loss: 0.02502911913424392
Epoch2, Batch 5000 loss: 0.02480070326793023
Epoch2, Batch 7000 loss: 0.024749569835552813
Epoch3, Batch 1000 loss: 0.029025374579812625
Epoch3, Batch 3000 loss: 0.024565998178689485
Epoch3, Batch 5000 loss: 0.024472941530646122
Epoch3, Batch 7000 loss: 0.024387568443041793
Epoch4, Batch 1000 loss: 0.028627742407629227
Epoch4, Batch 3000 loss: 0.0242278724147746
Epoch4, Batch 5000 loss: 0.024163253741676074
Epoch4, Batch 7000 loss: 0.02418276365141656
Epoch5, Batch 1000 loss: 0.028395280779416977
Epoch5, Batch 3000 loss: 0.023975891152231157
Epoch5, Batch 5000 loss: 0.02396302072005053
Epoch5, Batch 7000 loss: 0.023870536353556127
Epoch6, Batch 1000 loss: 0.02298555027290487
Epoch6, Batch 3000 loss: 0.01414467300243672

In [20]:
# Test
example_path = paths[500]
t = 1000
Swaptions = [example_path.Swaptions[i][t] for i in range(1,10)]
Q_s = [example_path.Q_s[i][t] for i in range(1,10)]
sample = np.concat([Swaptions,Q_s])
print(sample)
autoencoder.preprocess(sample)
print(sample)
print("---------------------")
k = autoencoder.encoder(th.from_numpy(sample))
print(k)
print("---------------------")
recovered = autoencoder.decoder(k)
print(recovered)
print(autoencoder.deprocess(recovered.detach()))

[0.         0.         0.         0.         0.         0.
 0.         0.01688612 0.00883604 1.         1.         1.
 1.         1.         1.         1.         0.99530694 0.98107173]
[-4.60517019 -4.60517019 -4.60517019 -4.60517019 -4.60517019 -4.60517019
 -4.60517019 -3.61614515 -3.97198325  1.          1.          1.
  1.          1.          1.          1.          0.99061389  0.96214346]
---------------------
tensor([-0.3207, -0.4160, -0.3349], dtype=torch.float64,
       grad_fn=<LeakyReluBackward0>)
---------------------
tensor([-4.6070, -4.6024, -4.6038, -4.6132, -4.6322, -4.1272, -3.9853, -3.9871,
        -4.1143,  1.0000,  1.0001,  1.0000,  1.0004,  0.9996,  0.9774,  0.9508,
         0.9231,  0.8947], dtype=torch.float64, grad_fn=<LeakyReluBackward0>)
tensor([-1.8365e-05,  2.7631e-05,  1.3934e-05, -7.9763e-05, -2.6652e-04,
         6.1286e-03,  8.5860e-03,  8.5526e-03,  6.3376e-03,  1.0000e+00,
         1.0000e+00,  9.9999e-01,  1.0002e+00,  9.9978e-01,  9.8872e-01,
       

In [9]:
with open("autoencoderT","wb") as fp:
    pickle.dump(autoencoder,fp)